---
driver:
  name: gce
  region: <%= ENV.fetch('GOOGLE_REGION', 'us-central1') %>
  project: <%= ENV.fetch('GOOGLE_PROJECT_ID', 'dev-fortress-92118') %>
  disks:
    disk0:
      boot: true
      disk_size: 40
  tags: ['created-by-test-kitchen']
  use_private_ip: <%= ENV.fetch('GOOGLE_USE_PRIVATE_IP', false) %>

provisioner:
  chef_omnibus_root: /opt/chef
  product_name: chef
  install_strategy: skip

transport:
  username: <%= ENV.fetch('GOOGLE_SSH_USERNAME', ENV['USER']) %>
  ssh_key: <%= ENV.fetch('GOOGLE_SSH_KEY', File.expand_path('~/.ssh/kitchen-gce')) %>

platforms:
  - name: ubuntu-20.04
    driver:
      image_project: <%= ENV.fetch('GOOGLE_IMAGE_PROJECT', 'prodeng-robotic-cook') %>
      image_family: <%= ENV.fetch('GOOGLE_IMAGE_FAMILY_XENIAL', 'fastly-rc-focal') %>
