---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04

suites:
  - name: default
    run_list:
      - recipe[fst_app_terraform_enterprise_test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
